# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icons = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/cyPark95"

[social.params]
icon = "brand-github"

[[social]]
identifier = "gmail"
name = "Gmail"
url = "cas15987@gamil.com"

[social.params]
icon = "mail"
